export enum OrgState {
    InitialFocusOnSmartbar = 1,
    AddName = 2,
    AddJobTitle = 3,
    PressEnter = 4,
    RightArrow = 5,
    DownArrow = 6,
    LeftArrow = 7,
    UpArrow = 8,
    MoveNode = 9,
    AssignNode = 10,
    EditNode = 11,
    SaveNode = 12,
    DeleteNode = 13,
}